# Generated by Django 3.2.9 on 2021-11-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default='user', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.region'),
        ),
    ]
