# Generated by Django 3.2.9 on 2021-11-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
